from app.engines.llm_engine import ask_llm

def generate_detailed_strategic_plan(analytics, insights, strategy, pricing_opt=None):
    """
    Asks the AI to generate a comprehensive, multi-page level strategic business plan.
    """
    context = f"""
        You are a Senior Strategic Business Consultant.
        Based on the following data points, generate a highly detailed, professional, and actionable Strategic Business Plan.

        DATA SUMMARY:
        {analytics}

        INITIAL INSIGHTS:
        {insights}

        PROPOSED STRATEGIES:
        {strategy}

        RL PRICING OPTIMIZATION RESULTS:
        {pricing_opt}

        The report MUST be structured with the following sections:
        1. EXECUTIVE SUMMARY (High-level overview)
        2. MARKET PERFORMANCE ANALYSIS (Deep dive into revenue and regional data)
        3. PRODUCT & INVENTORY STRATEGY (Optimization of top offerings)
        4. PRICING OPTIMIZATION STRATEGY (Explain the RL model's recommended price adjustment)
        5. OPERATIONAL EFFICIENCY (Margin improvement and cost control)
        6. 12-MONTH STRATEGIC ROADMAP (Phased implementation plan: Q1-Q4)
        7. RISK ASSESSMENT & MITIGATION

        Format the response in clear Markdown with professional headings. Use a formal and authoritative tone.
    """
    
    try:
        plan = ask_llm(context)
        if "unavailable" in plan.lower() or "ollama" in plan.lower():
             return _generate_fallback_plan(analytics, insights, strategy, pricing_opt)
        return plan
    except:
        return _generate_fallback_plan(analytics, insights, strategy, pricing_opt)

def _generate_fallback_plan(analytics, insights, strategy, pricing_opt=None):
    pricing_str = f"Recommended Price Adjustment: {pricing_opt.get('best_price_adjustment_percent')}%" if pricing_opt else "Pricing optimization data unavailable."
    
    return f"""
# DETAILED STRATEGIC PLAN (Generated by NeuralBI Pro)

## 1. Executive Summary
The business shows a total revenue of ${analytics.get('total_revenue', 0):,.2f} across {analytics.get('rows', 0)} transactions.

## 2. Market Performance
{chr(10).join(['- ' + i for i in insights])}

## 3. Pricing & Yield Strategy
{pricing_str}

## 4. Recommended Roadmap
{chr(10).join(['- ' + s for s in strategy])}
    """
